sonar.projectKey=pnpm-node-app
sonar.projectName=pnpm-node-app

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info