apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-deployment
  labels:
    app: cicd-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      # Fixes S6865: Disables mounting default ServiceAccount tokens into the pod
      automountServiceAccountToken: false
      containers:
        - name: cicd-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Fixes container resource request issues (Memory, Storage, CPU)
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"